theme: jekyll-theme-cayman

intro:
title: Optimization Foundation for Reinforcement Learning
description: Workshop at NeurIPS 2019, Dec 14th, 2019
location: Ballroom A, Vancouver Convention Center, Vancouver, Canada
