theme: jekyll-theme-cayman

intro:
title: Optimization Foundation for Reinforcement Learning
description:
- Workshop at NeurIPS, Dec 13-14th. 2019, Vancouver, Canada
# buttons:
#   Speakers: '#speakers'
#   Dates: '#dates'
#   Schedule: '#schedule'
#   # Submissions: '#submissions'
#   Papers: '#accepted-papers'
#   Organizers: '#organizers'