theme: jekyll-theme-cayman

intro:
title: Optimization Foundation of Reinforcement Learning
description: Workshop at NeurIPS 2019, Dec 14th, 2019
location: West Ballroom A, Vancouver Convention Center, Vancouver, Canada
